### ISSUE TITLE
bug: scalar custom nested subfield selections should be expanded

### ISSUE THREAD

**Issue by yyyyaaa** [launchql/launchql-gen#29]
Query:
```
const result = client
    .query('ActionGoal')
    .getMany({
      select: {
        action: {
          select: {
            id: true,
            slug: true,
            photo: true,
            shareImage: true,
            title: true,
            titleObjectTemplate: true,
            url: true,
            description: true,
            discoveryHeader: true,
            discoveryDescription: true,
            notificationText: true,
            notificationObjectTemplate: true,
            enableNotifications: true,
            enableNotificationsText: true,
            search: true,
            location: true,
            locationRadius: true,
            timeRequired: true,
            startDate: true,
            endDate: true,
            approved: true,
            published: true,
            isPrivate: true,
            rewardAmount: true,
            activityFeedText: true,
            callToAction: true,
            completedActionText: true,
            alreadyCompletedActionText: true,
            selfVerifiable: true,
            isRecurring: true,
            recurringInterval: true,
            oncePerObject: true,
            minimumGroupMembers: true,
            limitedToLocation: true,
            tags: true,
            createdBy: true,
            updatedBy: true,
            createdAt: true,
            updatedAt: true,
            groupId: true,
            ownerId: true,
            objectTypeId: true,
            rewardId: true,
            verifyRewardId: true
          }
        },
        goal: {
          select: {
            id: true,
            name: true,
            slug: true,
            shortName: true,
            icon: true,
            subHead: true,
            tags: true,
            search: true,
            createdBy: true,
            updatedBy: true,
            createdAt: true,
            updatedAt: true
          }
        }
      }
    })
    .print();
```

Expected: output should further expand `location { x y }`, `timeRequired`...etc of custom types
Actual: `location` is just `location`, no sub fields

**Comment by yyyyaaa** [comment]
hey @pyramation this is blocking me so i'm prioritizing fixing this, not a big bug, PR soon

**Comment by pyramation** [comment]
@yyyyaaa I just realized, we may want to return `geojson` instead of `x,y` because of cases where it ends up being a Polygon instead of a Point. Maybe you handled that case, but I think the `geojson` field handles all of them

**Comment by yyyyaaa** [comment]
@pyramation good point, I'll have it return `{ geojson x y }`

**Comment by yyyyaaa** [comment]
actually it's already handled, I returned all

**Comment by pyramation** [comment]
I believe for other types like `GeometryCollection` and `GeoPolygon`, they don't have `x,y` fields, so we probably should just use `geojson`?

Otherwise the `x,y` would throw an error for those types.

**Comment by pyramation** [comment]
They all support `geojson`

<img width="248" alt="Screen Shot 2021-05-01 at 9 56 39 PM" src="https://user-images.githubusercontent.com/545047/116802512-4b64a400-aac8-11e
<img width="268" alt="Screen Shot 2021-05-01 at 9 57 24 PM" src="https://user-images.githubusercontent.com/545047/116802515-4c95d100-aac8-11eb-95d3-3e6dd7f751b9.png">
b-8353-e6475e8c61f5.png">
<img width="266" alt="Screen Shot 2021-05-01 at 9 57 06 PM" src="https://user-images.githubusercontent.com/545047/116802514-4c95d100-aac8-11eb-92b6-43133123d42f.png">


We could start trying to look at which postgis type it is, and support each one also, but maybe the `geojson` is the simpler approach to cover all cases now without having errors later? Let me know your thoughts
